version: "3.9"

services:
  nginx:
    image: nginx:1.23
    volumes:
      - ./nginx/templates:/etc/nginx/templates
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    environment:
      - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.conf
      - SERVER_NAME=${SERVER_NAME}
      - GRAPHQL_PORT=${APOLLO_PORT}
      - NEXTJS_PORT=${NEXTJS_PORT}
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./mongodb/db:/data/db
    ports:
      - ${MONGO_PORT}:27017
  apollo-server:
    build:
      context: ../
      dockerfile: ./.docker/prod.Dockerfile
      target: apollo-server
    restart: always
    environment:
      PORT: ${APOLLO_PORT}
    ports:
      - ${APOLLO_PORT}:${APOLLO_PORT}
  web-application:
    build:
      context: ../
      dockerfile: ./.docker/prod.Dockerfile
      target: coctail-web-app
    restart: always
    environment:
      PORT: ${NEXTJS_PORT}
    ports:
      - ${NEXTJS_PORT}:${NEXTJS_PORT}